server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE

spring:
  cloud:
    gateway:
      routes:
        - id: cliente-route
          uri: lb://CLIENTE-SERVICE
          predicates:
            - Path=/api/v1/clientes, /api/v1/clientes/**
        - id: paquete-route
          uri: lb://PAQUETE-SERVICE
          predicates:
            - Path=/api/v1/paquetes, /api/v1/paquetes/**, /api/v1/categorias, /api/v1/paquetes/**
        - id: tracking-route
          uri: lb://TRACKING-SERVICE
          predicates:
            - Path=/api/v1/tracking, /api/v1/tracking/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/