server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cliente_db
    username: postgres
    password: ima
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
reniec:
  api:
    token: "sk_14403.36vBAyzXyTo1BohgGRBoJJ6ku5oS6X9c"